const card_content = [
  {
    id: 1,
    title: 'Grow Together',
    body: 'Connect with neighbors near and far in local permaculture/gardening groups to learn from one another and share growing tips that you\'ve found throughout the years!',
    image: 'friendly_green_neighbors.jpeg',
  },
  {
    id: 2,
    title: 'Connect Online',
    body: 'Look at the interactive map for people near you to trade food with! You\'ll be able to see what they have to trade and you\'ll be able to put your excess produce on your own profile which is available for others to see in your area, making trading seamless and convenient!',
    image: 'bountifulharvest.jpeg',
  },
  {
    id: 3,
    title: 'card number 3 mah lord!',
    body: "princessss Fionaaaa",
    image: 'This is an iamge. A Picture is supposed to be here',
  },
]

const produce_content = [
  "Lettuce", 
  "Tomato", 
  "Spinach", 
  "Beets", 
  "Zuchinni", 
  "Chamomile", 
  "Sunflower seeds", 
  "Pumpkins", 
  "Melons", 
  "Echinacea",
  "Cilantro",
  "Carrots",
  "Potatoes",
  "Summer Squash",
  "Gourds",
  "Milk",
  "Eggs",
  "Cheese",
  "Kombucha",
  "Kiefer",
  "Apples",
  "Pears",
  "Strawberries",
  "Mullberries",
  "Plums",
  "Almonds",
  "Peachers",
  "Honey",
  "Sweet Peppers",
  "Hot Peppers",
  "Corn",
  "Asparagus",
  "Cabbages",
  "Brussel Sprouts",
  "Garlic",
  "Onions",
  "Sweet Potatoes",
  "Radishes",
  "Turnips",
  "Basil",
  "Lemon Balm",
  "Mint",
  "Calendula", 
  ""]

export {card_content, produce_content};
